package za.ac.cput.factory.review;

/* MobileGlow Car Wash
   Service Review Factory Test
   Author: Inga Zekani (221043756)
 */

import org.junit.jupiter.api.Test;
import za.ac.cput.domain.review.ServiceReview;

import java.util.Date;

import static org.junit.jupiter.api.Assertions.*;

class ServiceReviewFactoryTest {

    @Test
    void testCreateServiceReview_Success() {
        Date reviewDate = new Date();
        ServiceReview review = ServiceReviewFactory.createServiceReview(5, "Excellent service!", reviewDate);

        assertNotNull(review);
        assertEquals(5, review.getRating());
        assertEquals("Excellent service!", review.getComments());
        assertEquals(reviewDate, review.getReviewDate());
        assertNull(review.getReviewID()); // ID should be null (generated by DB)
    }

    @Test
    void testCreateServiceReview_InvalidRating() {
        Date reviewDate = new Date();
        ServiceReview review = ServiceReviewFactory.createServiceReview(6, "Excellent service!", reviewDate);

        assertNull(review); // Should be null due to invalid rating
    }
    
}
