package za.ac.cput.factory.booking;

import org.junit.jupiter.api.Test;
import za.ac.cput.domain.booking.CleaningService;

import static org.junit.jupiter.api.Assertions.*;

public class CleaningServiceFactoryTest {

    @Test
    public void testCreateSingleCleaningService() {
        CleaningService cs_1 = CleaningServiceFactory.createCleaningService(
                "ENGINE_CLEANING",
                500,
                2.5,
                "Exterior Wash"
        );

        assertNotNull(cs_1); // Ensure object is created
        assertEquals("ENGINE_CLEANING", cs_1.getServiceName());
        assertEquals("Exterior Wash", cs_1.getCategory());
        assertTrue(cs_1.getPriceOfService() > 0);

        System.out.println("Single cleaning service created:\n" + cs_1);
    }

    @Test
    public void testCreateMultipleCleaningServices() {
        CleaningService cs_1 = CleaningServiceFactory.createCleaningService(
                "WAXING_AND_POLISHING",
                300,
                1.5,
                "Exterior Care"
        );

        CleaningService cs_2 = CleaningServiceFactory.createCleaningService(
                "CERAMIC_COATING",
                700,
                2.0,
                "Paint Protection"
        );

        assertNotNull(cs_1);
        assertNotNull(cs_2);
        // Since ID is generated by JPA, it might be null until persisted, so don't compare it here
        assertEquals("Exterior Care", cs_1.getCategory());
        assertEquals("Paint Protection", cs_2.getCategory());

        System.out.println("Multiple cleaning services created:\n" + cs_1 + "\n" + cs_2);
    }
}